name: MabMade
favicon: null
layout_spectrum: 0.59266
typography_spectrum: 1
title: Mab Made
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25201d'
    - '#bf8967'
    - '#f7f4e5'
    - '#e1b58e'
    - '#73452d'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25369230122305453
purpose: []
