name: MabMade
favicon: null
layout_spectrum: 0.59266
typography_spectrum: 0.7519301532302052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.625
  lightness: 0.44736650795675814
  saturation: 0.5
  rhythmicContrast: 0.25369230122305453
purpose: []
